version: '2'
services:
  nyc.social.dockerfully.com:
    container_name: nyc.social.dockerfully.com
    image: dockerfully/diaspora:latest 
    build:
      context: ../
    links:
      - postgres-nyc
      - redis-nyc
    volumes:
      - diaspora-images-nyc:/home/diaspora/diaspora/public/uploads/images
      - ./diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml:ro
      - ./database.yml:/home/diaspora/diaspora/config/database.yml:ro
    ports:
      - '3059:3059'
    restart: always
    environment:
      - VIRTUAL_HOST=nyc.social.dockerfully.com
      - LETSENCRYPT_HOST=nyc.social.dockerfully.com
    networks:
      - mongonet
    restart: always




  postgres-nyc:
    container_name: postgres-nyc
    read_only: false
    mem_limit: 8G
    image: 'bitnami/postgresql:11'
    tmpfs:
    - /tmp
    ports:
      - '5550:5550'
    volumes:
      - 'postgresql_data-nyc:/bitnami/postgresql'
      - 'postgres-nyc:/var/lib/postgresql/data'
      - 'postgres-run-nyc:/var/run/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
#      - 'POSTGRES_PASSWORD=somepassword123'
      - 'POSTGRES_DATABASE=diaspora_production'
      - 'POSTGRES_USERNAME=diaspora'
      - 'POSTGRESQL_PORT_NUMBER=5550'
    restart: always
    networks:
      - mongonet



  redis-nyc:
    container_name: redis-nyc
    image: dockerfully/redis:latest
    build:
      context: ../redis/5.0
    mem_limit: 384M
    read_only: false
    tmpfs:
    - /tmp
    command: redis-server --port 6399 --appendonly yes
    volumes:
      - redis-nyc:/data
    restart: always
    networks:
      - mongonet



volumes:
  diaspora-images-nyc:
  postgres-nyc:
  postgres-run-nyc:
  redis-nyc:
  postgresql_data-nyc:
    driver: local


networks:
  mongonet:
    external: true
