version: '2'
services:
  iowa.social.dockerfully.com:
    container_name: iowa.social.dockerfully.com
    image: dockerfully/diaspora:latest 
    build:
      context: ../
    links:
      - postgres-iowa
      - redis-iowa
    volumes:
      - diaspora-images-iowa:/home/diaspora/diaspora/public/uploads/images
      - ./diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml:ro
      - ./database.yml:/home/diaspora/diaspora/config/database.yml:ro
    ports:
      - '3069:3069'
    restart: always
    environment:
      - VIRTUAL_HOST=iowa.social.dockerfully.com
      - LETSENCRYPT_HOST=iowa.social.dockerfully.com
    networks:
      - mongonet
    restart: always




  postgres-iowa:
    container_name: postgres-iowa
    read_only: false
    mem_limit: 8G
    image: 'bitnami/postgresql:11'
    tmpfs:
    - /tmp
    ports:
      - '5566:5566'
    volumes:
      - 'postgresql_data-iowa:/bitnami/postgresql'
      - 'postgres-iowa:/var/lib/postgresql/data'
      - 'postgres-run-iowa:/var/run/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
#      - 'POSTGRES_PASSWORD=somepassword123'
      - 'POSTGRES_DATABASE=diaspora_production'
      - 'POSTGRES_USERNAME=diaspora'
      - 'POSTGRESQL_PORT_NUMBER=5566'
    restart: always
    networks:
      - mongonet



  redis-iowa:
    container_name: redis-iowa
    image: dockerfully/redis:latest
    build:
      context: ../redis/5.0
    mem_limit: 384M
    read_only: false
    tmpfs:
    - /tmp
    command: redis-server --port 7899 --appendonly yes
    volumes:
      - redis-iowa:/data
    restart: always
    networks:
      - mongonet



volumes:
  diaspora-images-iowa:
  postgres-iowa:
  postgres-run-iowa:
  redis-iowa:
  postgresql_data-iowa:
    driver: local


networks:
  mongonet:
    external: true
