version: '2'
services:
  sandiego.social.dockerfully.com:
    container_name: sandiego.social.dockerfully.com
    image: dockerfully/diaspora:latest 
    build:
      context: ../
    links:
      - postgres-sandiego
      - redis-sandiego
    volumes:
      - diaspora-images-sandiego:/home/diaspora/diaspora/public/uploads/images
      - ./diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml:ro
      - ./database.yml:/home/diaspora/diaspora/config/database.yml:ro
    ports:
      - '3070:3070'
    restart: always
    environment:
      - VIRTUAL_HOST=sandiego.social.dockerfully.com
      - LETSENCRYPT_HOST=sandiego.social.dockerfully.com
    networks:
      - mongonet
    restart: always




  postgres-sandiego:
    container_name: postgres-sandiego
    read_only: false
    mem_limit: 8G
    image: 'bitnami/postgresql:11'
    tmpfs:
    - /tmp
    ports:
      - '5567:5567'
    volumes:
      - 'postgresql_data-sandiego:/bitnami/postgresql'
      - 'postgres-sandiego:/var/lib/postgresql/data'
      - 'postgres-run-sandiego:/var/run/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
#      - 'POSTGRES_PASSWORD=somepassword123'
      - 'POSTGRES_DATABASE=diaspora_production'
      - 'POSTGRES_USERNAME=diaspora'
      - 'POSTGRESQL_PORT_NUMBER=5567'
    restart: always
    networks:
      - mongonet



  redis-sandiego:
    container_name: redis-sandiego
    image: dockerfully/redis:latest
    build:
      context: ../redis/5.0
    mem_limit: 384M
    read_only: false
    tmpfs:
    - /tmp
    command: redis-server --port 7900 --appendonly yes
    volumes:
      - redis-sandiego:/data
    restart: always
    networks:
      - mongonet



volumes:
  diaspora-images-sandiego:
  postgres-sandiego:
  postgres-run-sandiego:
  redis-sandiego:
  postgresql_data-sandiego:
    driver: local


networks:
  mongonet:
    external: true
